### ISSUE TITLE
[Bug]especially consumes performance

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-math#228]
This plugin especially consumes performance, especially when reading pdf, there will be obvious lag, please improve, thank you very much.

**Comment by RyotaUshio** [comment]
@math-feng 

> especially when reading pdf

This plugin doesn't touch any part of the PDF viewer. Isn't it due to PDF++ rather than this plugin?

BTW I've just released a new beta version of PDF++, which addresses the performance issue reported in the PDF++ repository:
https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.39.14-beta0

Does this help?

**Comment by math-feng** [comment]
There was a marked improvement! Thank you very much!

**Comment by math-feng** [comment]
Can this plugin be maintained again? After all, the plugin PDF++ has worked very well.

**Comment by RyotaUshio** [comment]
This plugin is not abandoned. I'm just not good at doing multiple things at one time, and also I'm a bit busy with my real work. Will be back to this project a few months later.
